# Generated by Django 2.0.4 on 2018-05-14 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('libros', '0005_auto_20180514_2023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Apellido y nombre')),
                ('dni', models.CharField(help_text="Por favor coloque los '.' en el nro de dni", max_length=11, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('domicilio', models.CharField(blank=True, max_length=50, null=True)),
                ('docente', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Lectores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prestamo', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Retiro')),
                ('fecha_devuelto', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Devolución')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libros.Libro')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prestamos.Lector')),
            ],
            options={
                'ordering': ['fecha_prestamo'],
            },
        ),
    ]
