# Generated by Django 2.0.4 on 2018-04-23 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0003_auto_20180423_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='nombre',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
