# Generated by Django 2.0.4 on 2018-05-14 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0004_auto_20180423_2054'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='submateria',
            unique_together={('nombre', 'materia')},
        ),
    ]
