# Generated by Django 2.0.4 on 2018-06-11 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0005_auto_20180514_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='codigo',
            field=models.CharField(default='error', max_length=14, unique=True),
            preserve_default=False,
        ),
    ]
